Adding some more guards to protect against missing data
Ran into the following error while processing performance statistics:
```python
Traceback (most recent call last):
File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "process.py", line 90, in createsummary
summary,timeseries = summarize.summarize(job, lariat)
File "/home/xdmod/tacc_stats/pickler/summarize.py", line 615, in summarize
ndatapoints = len(host.stats[metricname][device][:,index])
IndexError: index 6 is out of bounds for axis 1 with size 3
```

Applied the same technique as was used previously to bound check before
accessing elements of an array.